### ISSUE TITLE
复刻draw.io

### ISSUE THREAD

**Issue by liuhuancom** [le5le-com/topology#1]
你这是要复刻一个drwa.io吗？

**Comment by Alsmile** [comment]
@liuhuancom 看了下，还真的好像，目前很多功能和细节比我强好多。要复刻的话，还有很多工作。

技术上他是 dom svg，我是canvas。

其实，我最初看到的是jtopo，觉得不开源，还不是特别满足要求。后又看到processon，但是无法用在自己的项目中。

最后，整理了下思路，决定用  绘图引擎 + 图形库中间件的方式去实现一个。

**Comment by liuhuancom** [comment]
draw.io 是可以用在自己的项目中的，不过我更建议你用WebAssembly的方式来做，性能更好而且也是趋势
