### ISSUE TITLE
组合多个节点时的疑问

### ISSUE THREAD

**Issue by goforward01** [le5le-com/topology#124]
问题： 组合有时不生效，变成包含关系，导致无法取消“组合”
前言：
    感谢开源，非常棒的开源库，支持齐全的操作，良好的扩展性，赞!
版本：
    "@topology/core": "^0.2.30",
    "@topology/activity-diagram": "^0.2.24",
    "@topology/class-diagram": "^0.2.24",
    "@topology/flow-diagram": "^0.2.24",
    "@topology/sequence-diagram": "^0.2.24",
    "@topology/chart-diagram": "^0.2.24",
    "@topology/layout": "^0.2.24"
复现过程：
   创建两个矩形节点A和B，出现以下几种情况
   1). 当A节点完全包含B节点时，框选两个节点，然后组合，此时单击组合后节点，显示节点的name是rectangle，而不是combine
   2). 当A节点部分包含B节点时，同样操作，单击组合后节点，显示节点的name为combine
   3). 当A节点和B节点不交叉时，同样操作，单击组合后节点，显示节点的name为combine
  针对1)无法执行取消组合操作，因为canvas中data下的pens，是以A为父节点，B为child的方式存在的
调用的方法：(取自项目topology-vue)
  `onCombine(stand) { // stand 默认为false
      if (!this.props.nodes) {
        return
      }
      this.canvas.combine(this.props.nodes, stand)
      this.canvas.render()
    },

    onUncombine() {
      if (!this.props.node) {
        return
      }
      this.canvas.uncombine(this.props.node)
      this.canvas.render()
    }`
疑问：
  [在官网的演示界面中(http://topology.le5le.com/workspace)，即angular版本的调用中，不会出现此类问题。angular版本中只有组合操作，没有包含的操作。不知是否是我使用方式有问题。看了下源码core.ts中关于combine的函数代码：
`combine(pens?: Pen[], stand = false) {
    if (!pens) {
      pens = this.activeLayer.pens;
    }

    const rect = this.getRect(pens);
    for (const item of pens) {
      const i = this.findIndex(item);
      if (i > -1) {
        this.data.pens.splice(i, 1);
      }
    }

    let node = new Node({
      name: 'combine',
      rect: new Rect(rect.x, rect.y, rect.width, rect.height),
      text: '',
      paddingLeft: 0,
      paddingRight: 0,
      paddingTop: 0,
      paddingBottom: 0,
      strokeStyle: 'transparent',
      children: [],
    });

    for (let i = 0; i < pens.length; ++i) {
      if (pens[i].type === PenType.Node && rect.width === pens[i].rect.width && rect.height === pens[i].rect.height) {
        node = pens[i] as Node; // 此处不太明白为何还是操作node
        if (!node.children) {
          node.children = [];
        }
        pens.splice(i, 1);
        break;
      }
    }

    for (const item of pens) {
      item.stand = stand;
      item.parentId = node.id;
      item.calcRectInParent(node);
      node.children.push(item);
    }
    this.data.pens.push(node);

    this.activeLayer.setPens([node]);

    this.dispatch('node', node);

    this.cache();
  }`

**Comment by Alsmile** [comment]
就是这样设计的：某个节点区域完全包含其他节点时，取当前节点为父节点；否则新增一个“虚拟节点作为父节点”。

任意存在children的节点，都是组合节点，都可以取消组合。因此，应该都能取消组合才对
