### ISSUE TITLE
对已连线的点使用spaceBetween进行布局操作后，连线会脱离节点，但是再次移动节点后恢复正常

### ISSUE THREAD

**Issue by lianzhidong** [le5le-com/topology#126]
代码如下：
`    //水平均匀分布
    onSpaceBetween() {
      //第二个参数为间隔距离
      spaceBetween(this.canvas.activeLayer.pens, 500)
      this.canvas.render()
      // 新增历史记录，方便undo
      this.canvas.cache()
    },`

**Comment by Alsmile** [comment]
spaceBetween只做位置改变，再调用一下topology.updateProps();去处理关联数据
