### ISSUE TITLE
时序图放大以后就没办法看到左边部分区域了，导致时序图比较大的时候无法编辑左边的区域

### ISSUE THREAD

**Issue by sunysmile** [le5le-com/topology#132]
![image](https://user-images.githubusercontent.com/47592973/99754193-dc4f5080-2b22-11eb-8b9d-15edd002e3ec.png)

**Comment by Alsmile** [comment]
目前是根据鼠标位置为中心缩放的，放大很自然有超出画布范围的情况，这是正常的。
