### ISSUE TITLE
时序图类图中，有时候两条线无法连接到一个锚点上，连接上以后拖动，其中一条线分离了。

### ISSUE THREAD

**Issue by Bruce-Ming** [le5le-com/topology#134]
如图
![image](https://user-images.githubusercontent.com/37186519/101302069-9fe75880-3875-11eb-99db-354a17ff4ece.png)

![image](https://user-images.githubusercontent.com/37186519/101302253-0c625780-3876-11eb-9216-84e2a9efb5e9.png)
先把第一条线取下来，再连上锚点，但是是虚的，无法连上

**Comment by Bruce-Ming** [comment]
https://user-images.githubusercontent.com/37186519/103392410-b329d300-4b58-11eb-8cdd-87c12d83d58c.mov

**Comment by Alsmile** [comment]
@0.2.24
