### ISSUE TITLE
npm  包 topology/core 0.3.17/0.3.18 import 路径错误，导致编译报错

### ISSUE THREAD

**Issue by wph888666** [le5le-com/topology#137]
ERROR in ../node_modules/@topology/core/src/middles/nodes/text.d.ts:2:21 - error TS2307: Cannot find module '@topology/core/models/pen'.

2 import { Pen } from '@topology/core/models/pen';

import 路径错误，导致编译报错

**Comment by Alsmile** [comment]
Not found

**Comment by Alsmile** [comment]
我们使用的是yarn workspaces目录结构，在源码根目录使用yarn安装依赖包即可。不要使用npm

如果需要运行example，再次用yarn在example下的项目根目录安装依赖包和运行
