### ISSUE TITLE
hover时的位置发生偏移

### ISSUE THREAD

**Issue by zhuzhu95** [le5le-com/topology#141]
当打开左侧二级菜单栏时，虽然画布往右偏移了，但是鼠标的hover事件还在之前的位置。0.3.20版本没有这个问题。

https://user-images.githubusercontent.com/34122127/103599951-47bd7800-4f41-11eb-8209-cc6e7786b2b3.mov

**Comment by Alsmile** [comment]
https://www.yuque.com/alsmile/topology/faq#fBiJY
