### ISSUE TITLE
release 0.3.24 Echarts 图表缩放不会自适应宽高了，并且是否默认连线类型由 fromArrowType 改成了 fromArrow ?

### ISSUE THREAD

**Issue by woowalker** [le5le-com/topology#152]
官方演示地址：http://topology.le5le.com/workspace
![image](https://user-images.githubusercontent.com/7894779/105113980-eed50e80-5b00-11eb-8faa-70cf909f2d64.png)
并且我发现，是不是默认的连线类型由之前的
fromArrowType 和 toArrowType 改成了 fromArrow 和 toArrow?
不知道是不是还有其他字段变更，好做数据兼容，麻烦大神告知下，感谢大神的付出。

**Comment by Alsmile** [comment]
fromArrowType 和 toArrowType 改成了 fromArrow 和 toArrow

0.4.0 font修过为：
![image](https://user-images.githubusercontent.com/1797302/108630717-2b4dae80-74a1-11eb-99cc-4a6726890089.png)
