### ISSUE TITLE
使用echart图表控件，setOption 画布上的图表不会更新，调用画布的 render 函数也无法更新

### ISSUE THREAD

**Issue by woowalker** [le5le-com/topology#158]
如题，必须刷新整个浏览器，才能看到效果

**Comment by Summer-andy** [comment]
可以暂时先使用 
```
     const result = new Blob([JSON.stringify(canvas.data)], { type: 'text/plain;charset=utf-8' });
      reader.readAsText(result, 'text/plain;charset=utf-8');
      reader.onload = (e) => {
        canvas.open(JSON.parse(reader.result));
      };
 ```

**Comment by woowalker** [comment]
> 可以暂时先使用
> 
> ```
>      const result = new Blob([JSON.stringify(canvas.data)], { type: 'text/plain;charset=utf-8' });
>       reader.readAsText(result, 'text/plain;charset=utf-8');
>       reader.onload = (e) => {
>         canvas.open(JSON.parse(reader.result));
>       };
> ```

这个思路是重新 open 一次数据，试了下还是不行，不过为了达到重新open一次数据，是不是没必要通过 Blob 然后再 read，是不是直接 cloneDeep 一下就行？不过数据量大的话，cloneDeep 会有性能问题就是了

**Comment by Summer-andy** [comment]
有示例代码仓库吗? 因为我不太清楚你的代码环境。

**Comment by Alsmile** [comment]
fixed @ 0.3.28
