### ISSUE TITLE
请问官网的图形库哪里可以查到对应数据

### ISSUE THREAD

**Issue by ccyytt** [le5le-com/topology#161]
感谢大佬的开源 工具做的非常棒，最近在尝试使用到实际业务中。 目前查看文档发现官网的左侧的图形数据从api文档里面无法查到全部（目前只有流程图，活动图，时序图，类图 4个库的组件公布）？请问哪里可以获取到相关信息。同时祝大佬越做越好。期待得到答复谢谢

**Comment by Alsmile** [comment]
其他的图形库，我们是作为企业图形收费的

**Comment by Alsmile** [comment]
其他的图形库，我们是作为企业图形收费的
