### ISSUE TITLE
【bug】新版本，鼠标滑轮滚动会缩放 ，es5版本。

### ISSUE THREAD

**Issue by ThreeLambs** [le5le-com/topology#162]
版本 "0.4.7" 鼠标滑轮滚动，画布会缩放  。正常情况下，按ctrl +鼠标滑轮 才会缩放。

**Comment by Alsmile** [comment]
默认操作就是改成这样了。如果不希望使用默认方式，可以在画布 选项 相关快捷键设置

**Comment by ThreeLambs** [comment]
> 默认操作就是改成这样了。如果不希望使用默认方式，可以在画布 选项 相关快捷键设置

不会弄，没找到咋配置。

`[优化]默认取消画布滚动条（改用大家熟悉的缩放移动显示其他区域）`
我觉得这不是优化，这叫路走歪了。
鼠标滑轮首选都是用来滚动滚动条的，用来缩放有点奇怪。区域切换还是弄个小地图比较靠谱。
