### ISSUE TITLE
[求助]怎么禁用节点文本和连线文本的双击编辑功能

### ISSUE THREAD

**Issue by ThreeLambs** [le5le-com/topology#163]
1. 怎么``禁用``节点文本和连线文本的``双击编辑``功能
2. 怎么禁用鼠标滚轮缩放，或设置为 ``ctrl``+滚轮 才缩放

**Comment by Alsmile** [comment]
文档都有
1. 画布 选项 hideInput
2. 画布 选项  scaleKey
https://www.yuque.com/alsmile/topology/canvas#EdpHv
