### ISSUE TITLE
0.3.28和0.4.11版本，保存为图片功能，保存下来的图片都无法查看

### ISSUE THREAD

**Issue by woowalker** [le5le-com/topology#165]
![image](https://user-images.githubusercontent.com/7894779/109736084-d6c3d500-7bfe-11eb-9eda-5567e5bbda07.png)
但是我看官方演示地址没有问题，想请问一下，我得选择哪个版本？

**Comment by woowalker** [comment]
找到原因了 @Alsmile 
![image](https://user-images.githubusercontent.com/7894779/109737415-ffe56500-7c00-11eb-9a5c-651a611fb3bf.png)

**Comment by Alsmile** [comment]
官网不能重现

**Comment by woowalker** [comment]
> 官网不能重现

我意思是文档参数顺序和源码不一致，文档是(name, type, quality)，源码是(name, padding, type, quality)
