### ISSUE TITLE
Warning: ~\node_modules\@topology\core\src\core.js depends on 'le5le-store'. CommonJS or AMD dependencies can cause optimization bailouts.

### ISSUE THREAD

**Issue by meiyoue** [le5le-com/topology#166]
![image](https://user-images.githubusercontent.com/80573265/111075251-0be6f600-8522-11eb-8cca-fa71c0356e20.png)

### Environment
Angular Project (ver.  11.2.5) Created By CLI

### Temp Fix: 
Close this warning.
https://angular.io/guide/build#configuring-commonjs-dependencies

### Expect
Hope le5le-store support es6 bundles for optimize.

**Comment by Alsmile** [comment]
1. cd the root of the source:  yarn
2. cd example/angular:  yarn
3.  yarn start
