### ISSUE TITLE
主页面使用Object节点嵌套Cavas子页面，会导致无法拖动左侧节点到画布上

### ISSUE THREAD

**Issue by DreamALittle** [le5le-com/topology#173]
单独打开Cavas所在页面可以正常使用。但是，当Cavas被另一个网页嵌套打开时，会发生无法拖动左侧工具栏节点到画布上的问题。感觉是因为window对象错误。window对象是主页面，而Canvas是超链接引用进来的。导致window对象识别不到window.topology

**Comment by Alsmile** [comment]
这个是html的iframe的相关知识，参考postmessage等相关页面间通信
