### ISSUE TITLE
节点增加动画，报错

### ISSUE THREAD

**Issue by ahahaihai** [le5le-com/topology#184]
刚使用，拷贝官方JSON可以实现，但是通过自己生产的JSON，加入节点动画后报错
![image](https://user-images.githubusercontent.com/82791185/117747373-a6bd3180-b240-11eb-8f18-bd2b4cce7fec.png)
![image](https://user-images.githubusercontent.com/82791185/117747432-bccaf200-b240-11eb-9d11-8d39b3d64067.png)

**Comment by dargon5210** [comment]
如何解决的 我也遇到该问题乐
