### ISSUE TITLE
特性: 缩略图功能

### ISSUE THREAD

**Issue by feitian124** [le5le-com/topology#186]
感谢提供这么好用的画图工具, 请问现在画布有缩略图功能吗?
类似 vscode 的代码缩略图, 提供缩略图功能可以在画布组件较多时,  可以更好的观察概框.

antv 的 x6 貌似提供这个功能: https://x6.antv.vision/apps/er/

![image](https://user-images.githubusercontent.com/1425383/118444268-7e8d7100-b71f-11eb-9ee5-de80d7ea822d.png)

**Comment by Alsmile** [comment]
现在没有，后面可以支持
