### ISSUE TITLE
0.5.17 背景图片无法保存

### ISSUE THREAD

**Issue by woowalker** [le5le-com/topology#188]
![image](https://user-images.githubusercontent.com/7894779/119450658-d2730800-bd66-11eb-944c-cb4552280322.png)
![image](https://user-images.githubusercontent.com/7894779/119450691-de5eca00-bd66-11eb-8f72-d785e43444a8.png)

**Comment by Alsmile** [comment]
最新版已修复

**Comment by Alsmile** [comment]
最新版已修复
