### ISSUE TITLE
为什么里面的动图只能保存png和svg的，不可以保存为gif-动态的？

### ISSUE THREAD

**Issue by SoftwareKing** [le5le-com/topology#19]
为什么里面的动图只能保存png和svg的，不可以保存为gif-动态的？

**Comment by Alsmile** [comment]
很好的建议，后面会加入

**Comment by Alsmile** [comment]
看了大多数开源js库，大多数用的是gif.js。但是这个只适合帧数不多的短gif，个人使用情况：
1. 帧数达到几百，会出现严重的内存问题，导致崩溃
2. 生成gif时间过长，甚至十几分钟人仍然没看到生成结果而放弃。

结论：暂时没发现好的开源的js的gif库，可能与js天生的性能短板有关。暂时不处理，有优秀的开源的js的gif库欢迎推荐，重开。

推荐使用免费的：ScreenToGif ，这个还是非常好用的。
