### ISSUE TITLE
文本背景生效， 节点背景没有生效

### ISSUE THREAD

**Issue by feitian124** [le5le-com/topology#194]
如下图， 本地文本背景生效， 节点背景没有生效。
今天在官网测试， 也有这个问题。

![image](https://user-images.githubusercontent.com/1425383/120881605-f22aeb80-c604-11eb-9c89-72eb5ec74844.png)

**Comment by feitian124** [comment]
经测试， text 组件不可以， 矩形组件可以

**Comment by Alsmile** [comment]
text本身只有文字，故没有大边框背景
