### ISSUE TITLE
动态开关

### ISSUE THREAD

**Issue by lhd951220** [le5le-com/topology#203]
如何实现根据不同的状态实现开关的开合动作呢

**Comment by Alsmile** [comment]
1，有不同的开关状态的节点，切换节点（修改name）
2，如果是节点图片，修改image属性
3，自定义图形库方式：自定义一个变量on，根据on的值，绘画不同的颜色

**Comment by lhd951220** [comment]
> 1，有不同的开关状态的节点，切换节点（修改name）
> 2，如果是节点图片，修改image属性
> 3，自定义图形库方式：自定义一个变量on，根据on的值，绘画不同的颜色

是不是需要修改源码，好像直接通过绘图无法实现
