### ISSUE TITLE
http://topology.le5le.com/assets/js/canvas2svg.js 404 Not Found

### ISSUE THREAD

**Issue by suishaojian** [le5le-com/topology#209]
本地部署le5le试用，界面有报错。
![image](https://user-images.githubusercontent.com/20984440/125921390-0d2826cf-74f4-4d1d-ae53-ef3f1abeaae3.png)

![image](https://user-images.githubusercontent.com/20984440/125921356-0ac4f371-1bd5-4916-9fbd-81c1b2333b19.png)

**Comment by SignDawn** [comment]
assets 去掉。
http://topology.le5le.com/js/canvas2svg.js
