### ISSUE TITLE
firefox浏览器拖拽图片节点会打开新tab页面

### ISSUE THREAD

**Issue by DeanTG** [le5le-com/topology#219]
环境：firefox
操作：拖拽节点进画布，icon 为 图片链接时，浏览器会自动打开图片链接的tab页。
参照：https://www.cnblogs.com/liulei-cherry/p/8440609.html
解决：在canvas ondrag 事件加上 e.stopPropagation()

**Comment by Alsmile** [comment]
看是否有插件

**Comment by SignDawn** [comment]
firefox canvas drawImage svg  , svg 根标签必须要有 width height 属性，https://stackoverflow.com/questions/38106906/canvas-drawimage-inline-svg-doesnt-work-on-firefox
新版本 topology.js 已经解决！
