### ISSUE TITLE
Advice add High DPI support

### ISSUE THREAD

**Issue by lihsai0** [le5le-com/topology#22]
See Detail: [Canvas High DPI](https://www.html5rocks.com/en/tutorials/canvas/hidpi/)

**Comment by Alsmile** [comment]
1. 线条、文字清晰度优化了，主要解决1px问题。（对动画渐变过程的选中框小数坐标无法对齐有轻微影响）
2. 现在高清屏中 Canvas 绘制图片 drawImage，不需要经过如上处理也不会出现模糊的情况了。参考： https://objcer.com/2017/10/10/High-DPI-Canvas-Render/

3. 上文提到的方案主要是canvas.ctx.scale，或人工放大文字倍数：
    - scale对鼠标交互有影响，位置坐标和绘图对不上，因此不能直接使用canvas.ctx.scale方案；
    - 人工缩放已经实现，即视图百分比

综上，暂时以第一条处理方案作为此issue的解决方案

**Comment by Alsmile** [comment]
暂时关闭（已处理线条、文字清晰度）。如果还有其他无法满足场景，请详细描述，并reopen。

**Comment by Alsmile** [comment]
文字清晰度比高清屏方案还是差点。后面等做性能压力的测试判断性能损失如何

**Comment by Alsmile** [comment]
已添加
