### ISSUE TITLE
[Bug]泳道图在当前缩放率时会没问题，缩放率一增加或缩小，泳道图就会错位

### ISSUE THREAD

**Issue by JackPennnnn** [le5le-com/topology#247]
before：
![1630482750(1)](https://user-images.githubusercontent.com/33740709/131633699-4bf65633-46af-4d87-b0be-bd81dd79e90a.jpg)

after：
![1630482796(1)](https://user-images.githubusercontent.com/33740709/131633779-d95a8f40-43ec-421b-9279-dfe003c005f2.jpg)

**Comment by SignDawn** [comment]
新版本有修复，尝试新官网  http://t.le5le.com/
