### ISSUE TITLE
Echarts loadjs永远不会执行

### ISSUE THREAD

**Issue by Curtion** [le5le-com/topology#266]
代码处： https://github.com/le5le-com/topology/blob/bf7b16acab2774299d94808889025cf1269fef74/packages/chart-diagram/src/register.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L6

逻辑应该是 ：`!echartsObjs.echarts && (echarts as any)` 吧

**Comment by SignDawn** [comment]
是的，有点问题，但不是这样更改，后一个是检测 window 下有没有 echarts 。
你先在 index.html 中引入 echarts 包吧

**Comment by SignDawn** [comment]
已修复，是判断 window 下是否有 echarts 属性
