### ISSUE TITLE
[suggestion]一些类的成员变量特定含义的值用枚举类型表示

### ISSUE THREAD

**Issue by giscafer** [le5le-com/topology#29]
- 建议一些属性值可以用枚举类型表示，或者源码加上注释，这样libs API生成的文档可以清晰明白可能的值代表含义。源码阅读体验会更好，也不需要更多文档支持，现在不看文档，源码没说明就没法了解到。

eg:  `Pen` 类的 `dash` 和 `Topology` 的`locked`，不看文档，单纯看源码不清楚其他值表示的意思。

![image](https://user-images.githubusercontent.com/8676711/69030243-ea4f2a80-0a11-11ea-9e8b-b0ca62ce02ba.png)

## 举例

```ts
export enum TopologyLockedType {
    Unlock = 0, // 未锁定，可任意编辑
    DisableLine = 1, // 锁定连线。不能编辑连线
    OnlySelectAndHighlight = -1, // 全部锁定，不能做任何编辑，允许选中，并高亮
    OnlyCanSelect = -2, // 全部锁定，不能做任何编辑，允许选中，无高亮
    Locked = -3 // 无法做任何操作
}

```

**Comment by shuaqq2004** [comment]
同意.. 用TS的目的也是为了更好的阅读和编写.
