### ISSUE TITLE
animateLayer 动画层级问题

### ISSUE THREAD

**Issue by EightDoor** [le5le-com/topology#300]
animateType="beads"    
**使用置顶、置底方法可以正常改变线条的层级关系**
top置顶
top(pen: Pen)
置顶一个节点/连线到画布顶层。

bottom置底
bottom(pen: Pen)
置底一个节点/连线到画布底层。
**但是播放动画后，动画一直在其他的节点最上方，使用top调整不生效，导致播放会覆盖住其他节点**
![image](https://user-images.githubusercontent.com/35022264/150486674-33937f0f-05d8-45e8-a59b-a7f20984fdf0.png)

**Comment by SignDawn** [comment]
是的，老版本是这样设计的，动画层在上面，会盖住下面的。
新版本 topology.js 不会出现这个问题。
![image](https://user-images.githubusercontent.com/48878568/150489808-750b2ef7-8d77-4715-b4b4-a17a9df7294f.png)

**Comment by EightDoor** [comment]
谢谢 我试试
