### ISSUE TITLE
polyline，自动计算多线段锚点，能否让折点居中，始终靠右看着不太舒服

### ISSUE THREAD

**Issue by shuangovo** [le5le-com/topology#302]

**Comment by SignDawn** [comment]
截个图，画个示意图

**Comment by shuangovo** [comment]
![image](https://user-images.githubusercontent.com/54254822/150899664-17515bee-13aa-4a6f-8e42-c0afad17c16c.png)
默认是上面的，我想要下面这样的

**Comment by SignDawn** [comment]
新版本吗？去新版本下面提一个 issue 吧，后续抽空看一下

**Comment by shuangovo** [comment]
嗯，1.0.1

**Comment by SignDawn** [comment]
去新版本下提一个吧， https://github.com/le5le-com/topology.js
这个我关闭了。
