### ISSUE TITLE
请问导入的文件只能是JSON格式的么？

### ISSUE THREAD

**Issue by liucien** [le5le-com/topology#31]
导入生成在本地的svg与png文件不生效

**Comment by Alsmile** [comment]
对的，json包含了丰富的数据：节点、连线、状态、锚点、动画、字体、视频资源、动画资源、图片资源、用户自定义数据等等。这些事svg和png无非描述的。

但是，svg和png可以作为图片节点导入，作为画布的一个节点：
[左侧工具栏]基本形状 -> image 图标拖入到画布，然后通过右侧属性栏，找到“图片”属性，上传自己的图片。

**Comment by liucien** [comment]
我现在的疑问是，我在官网上生成了一张png或者svg的流程图，但是我想导回去重新编辑，这个功能好像并没有
