### ISSUE TITLE
拖拽2个图形，放大或者缩小后，相同功能多次点击会造成位移

### ISSUE THREAD

**Issue by snk8828912** [le5le-com/topology#324]
应该是设置宽度高度时候，把坐标xy带进去了

**Comment by SignDawn** [comment]
新版本地址：https://github.com/le5le-com/topology.js ，下次提 issue 这个地址
下次提 issue ，把视频贴上。
已修复 ，等 1.1.7 版本

**Comment by snk8828912** [comment]
> 新版本地址：https://github.com/le5le-com/topology.js ，下次提 issue 这个地址 下次提 issue ，把视频贴上。 已修复 ，等 1.1.7 版本

了解
