### ISSUE TITLE
能否将项目中左边工具栏的iconfont独立出一个package?

### ISSUE THREAD

**Issue by awehook** [le5le-com/topology#36]
在使用过程中发现工具栏的iconfont是通过
    <link href="//at.alicdn.com/t/font_1113798_0532l8oa6jqp.css" rel="stylesheet" />
    <link href="//at.alicdn.com/t/font_1331132_5lvbai88wkb.css" rel="stylesheet" />
这样的方式来引用cdn 上的资源，
但是开发者在开发软件的过程中，比方说开发electron 应用或者vscode插件，希望将这些icon打包到应用中，也就是不走网络下载。因此请求，如果您有时间的话，能够方便将iconfont 独立成一个package 吗？
根据我的经验，将阿里的iconfont制作成一个npm package 非常简单，只需要在iconfont.cn网站上对应图标字体的工程里下载zip包，解压，然后将里面的文件放到npm 工程里面即可。
示例：https://github.com/awehook/blink-mind/tree/master/packages/icons

**Comment by awehook** [comment]
在使用过程中发现工具栏的iconfont是通过 //at.alicdn.com/t/font_1113798_0532l8oa6jqp.css
这样的方式来引用cdn 上的资源，但是开发者在开发软件的过程中，比方说开发electron 应用或者vscode插件，希望将这些icon打包到应用中，也就是不走网络下载。因此请求，如果您有时间的话，能够方便将iconfont 独立成一个package 吗？
根据我的经验，将阿里的iconfont制作成一个npm package 非常简单，只需要在iconfont.cn网站上对应图标字体的工程里下载zip包，解压，然后将里面的文件放到npm 工程里面即可。
示例：https://github.com/awehook/blink-mind/tree/master/packages/icons

**Comment by Alsmile** [comment]
在源码已经有了，参考https://github.com/le5le-com/topology/blob/master/src/index_local.html 的使用
