### ISSUE TITLE
请问怎么和php结合，我想要和php结合做一个在线脑图工具！

### ISSUE THREAD

**Issue by txb2d** [le5le-com/topology#37]
请问怎么和php结合，我想要和php结合做一个在线脑图工具！

**Comment by Alsmile** [comment]
这是一个纯前端的工具，建议参与前后端分离的方式去开发，把数据保存在服务器端。

canvas = new Topology(...)
直接canvas.data就是数据

前端显示画布后，用户绘画产生数据，通过canvas.data就可以获取，自己保存，下次canvas.open(data)就显示了
