### ISSUE TITLE
canvas图片不清晰

### ISSUE THREAD

**Issue by jinan5694** [le5le-com/topology#41]
![image](https://user-images.githubusercontent.com/3690120/72202057-f2699a80-3495-11ea-8d29-87dddeebe16c.png)
这个麻烦你统一解决以下吧。我不知道有没有更好的方案。
https://www.jianshu.com/p/28a28ddeeb5c

**Comment by Alsmile** [comment]
其实一直有这个逻辑处理。只是默认多加了一个0.25： window.devicePixelRatio / backingStorePixelRatio + 0.25

具体参考： https://www.yuque.com/alsmile/topology/canvas#EdpHv 中的extDpiRatio选项说明。

canvas的精度还是和svg或html有细微差别的
