### ISSUE TITLE
Typo: parse -> paste

### ISSUE THREAD

**Issue by CarterLi** [le5le-com/topology#49]
https://github.com/le5le-com/topology/blob/04a5a1cab9b3509efb44332e838eac152aac4c9e/libs/topology/index.ts#L1597

* parse: 解析
* paste: 粘贴

**Comment by Alsmile** [comment]
新版本中已修正

**Comment by CarterLi** [comment]
未看到最近有什么提交

**Comment by Alsmile** [comment]
确实没有代码提交，因为核心库有结构调整优化，核心库代码和一个新增强版本目前在同一个分支。但是新版本功能还需要一段时间才能完成。

所以，目前只暂时单独发布了npm库：topology-core@0.2.1-beta

**Comment by Alsmile** [comment]
version > 0.2.x
