### ISSUE TITLE
打包后运行不了

### ISSUE THREAD

**Issue by torlinpeng** [le5le-com/topology#55]

**Comment by torlinpeng** [comment]
打包后运行不了呢

**Comment by torlinpeng** [comment]
页面一直在加载
Access to script at '**file:///E:/runtime-es2015.d8d5c60e17c725000a90.js' from origin 'null'** has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
runtime-es2015.d8d5c60e17c725000a90.js:1 Failed to load resource: net::ERR_FAILED
index.html:1 Access to script at **'file:///E:/polyfills-es2015.85ea611aafc2ca9484ce.js**' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
polyfills-es2015.85ea611aafc2ca9484ce.js:1 Failed to load resource: net::ERR_FAILED
index.html:1 Access to script at **'file:///E:/main-es2015.0f38eaa8a3f8e89da331.js**' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

**Comment by Alsmile** [comment]
build后的文件，需要反向代理运行1. 本地用http
