### ISSUE TITLE
bkImage It doesn't seem to work properly

### ISSUE THREAD

**Issue by deyihu** [le5le-com/topology#56]
![XPB(VSO$82BX2AQ3~TTL YT](https://user-images.githubusercontent.com/25998927/77380745-ec0d6e00-6db6-11ea-8796-cd3d9bedf5dd.png)

No cross domain issues reported

bkColor can render normally

![F08MBAT8I1)7GG$ME% 076H](https://user-images.githubusercontent.com/25998927/77380892-5f16e480-6db7-11ea-88af-92bfbeb6056d.png)

**Comment by Alsmile** [comment]
required:   topology-core  >  0.2.1-beta

**Comment by deyihu** [comment]
@Alsmile 

Bkimage cannot be clear

```js
 //render bkimage success
   this.canvas.data.bkImage = 'http://localhost:9800/workstorge/personal/images/A600E431-A9EF-4139-BED1-617564300970timg.jpg';
   this.canvas.updateProps(node);

   // clear bkimage,Bkimage cannot be cleared
     this.canvas.data.bkImage=null;
     this.canvas.updateProps(node);
```

**Comment by Alsmile** [comment]
Clear bkimage:
this.canvas.clearBkImg();
this.canvas.render();
