### ISSUE TITLE
请问这个开源项目如何实现SCADA功能？

### ISSUE THREAD

**Issue by northeasternLiu** [le5le-com/topology#58]
和采集上来的数据是如何绑定的？我在文档中没看见 有这方面的教程
是后续要完善开发的吗？

**Comment by Alsmile** [comment]
数据绑定参考： https://www.yuque.com/alsmile/topology/pen 这个里面的data

目前，需要开发者去定制完善，参考： https://www.yuque.com/alsmile/topology/use 
https://www.yuque.com/alsmile/topology/faq#O7ntD

当然，可以期待正在开发企业版。

**Comment by Alsmile** [comment]
https://www.yuque.com/alsmile/topology/tigxys
