### ISSUE TITLE
Provides parameters for whether to draw lines automatically

### ISSUE THREAD

**Issue by deyihu** [le5le-com/topology#60]
In the process of drawing a figure, sometimes the drawing line is always triggered by mistake. Whether it can provide a parameter to disable the function of automatic drawing line? It is turned on when the line needs to be drawn. When drawing small figures, it's too obvious to touch them by mistake

绘制图形的过程中，有时总是误触发画线，能否提供一个参数禁用自动绘制线的功能，需要绘制直线的时候在开启。当绘制小的图形时，误触太明显了

**Comment by Alsmile** [comment]
options.hideAnchor
@topology-core@0.2.4-dev
