### ISSUE TITLE
关于新版本onMessage事件问题

### ISSUE THREAD

**Issue by janxy** [le5le-com/topology#69]
在官网提供的vue版本例子中锁定和解锁功能正常，升级0.2.6-dev版本后，解锁功能失效，在日志打印中发现onMessage事件中，锁定后的节点无法选中，导致switch (event)里面的event是space，，请问这个如何解决啊？

**Comment by aixinaxc** [comment]
同问

**Comment by aixinaxc** [comment]
0.2.7好像修复了

**Comment by Alsmile** [comment]
最新版已修复

**Comment by wangyangang** [comment]
从npm安装的最新版这么写：
this.canvasOptions.on = this.onMessage;
this.canvas = new Topology("topology", this.canvasOptions);
当点击画布时，不能触发onMessage方法，
使用0.5.3版本可以。
是最新版不这么写了吗？

**Comment by SignDawn** [comment]
1.0 版本重构了，new 以后 .on 即可，查看文档-消息事件 http://developer.le5le.com/topology-documents/tutorial/events.html
新版本 github 地址：https://github.com/le5le-com/topology.js
