### ISSUE TITLE
0.2.8版本组合问题

### ISSUE THREAD

**Issue by aixinaxc** [le5le-com/topology#71]
1、控件和连线一起组合后，连线和控件均无法被单独选中。
2、控件单独组合后，连线可以被选中，但是控件仍然不可被选中

**Comment by Alsmile** [comment]
选择子节点/连线，用shift + 单击。

shift + 单击： 单选，可用于选择子节点/连线。
ctrl + 单击： 多选。
ctrl + 单击鼠标按下不放（移动）：移动子节点。
